# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake

# The command to remove a file.
RM = /Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/apaget/Documents/HumanGL++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/apaget/Documents/HumanGL++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/apaget/.brew/Cellar/cmake/3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apaget/Documents/HumanGL++/CMakeFiles /Users/apaget/Documents/HumanGL++/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apaget/Documents/HumanGL++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HumanGl

# Build rule for target.
HumanGl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HumanGl
.PHONY : HumanGl

# fast build rule for target.
HumanGl/fast:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/build
.PHONY : HumanGl/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f third-party/glfw/CMakeFiles/uninstall.dir/build.make third-party/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f third-party/glfw/src/CMakeFiles/glfw.dir/build.make third-party/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/Bone.o: src/Bone.cpp.o

.PHONY : src/Bone.o

# target to build an object file
src/Bone.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Bone.cpp.o
.PHONY : src/Bone.cpp.o

src/Bone.i: src/Bone.cpp.i

.PHONY : src/Bone.i

# target to preprocess a source file
src/Bone.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Bone.cpp.i
.PHONY : src/Bone.cpp.i

src/Bone.s: src/Bone.cpp.s

.PHONY : src/Bone.s

# target to generate assembly for a file
src/Bone.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Bone.cpp.s
.PHONY : src/Bone.cpp.s

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Charactere.o: src/Charactere.cpp.o

.PHONY : src/Charactere.o

# target to build an object file
src/Charactere.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Charactere.cpp.o
.PHONY : src/Charactere.cpp.o

src/Charactere.i: src/Charactere.cpp.i

.PHONY : src/Charactere.i

# target to preprocess a source file
src/Charactere.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Charactere.cpp.i
.PHONY : src/Charactere.cpp.i

src/Charactere.s: src/Charactere.cpp.s

.PHONY : src/Charactere.s

# target to generate assembly for a file
src/Charactere.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Charactere.cpp.s
.PHONY : src/Charactere.cpp.s

src/Matrix.o: src/Matrix.cpp.o

.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i

.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s

.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Vec3.o: src/Vec3.cpp.o

.PHONY : src/Vec3.o

# target to build an object file
src/Vec3.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Vec3.cpp.o
.PHONY : src/Vec3.cpp.o

src/Vec3.i: src/Vec3.cpp.i

.PHONY : src/Vec3.i

# target to preprocess a source file
src/Vec3.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Vec3.cpp.i
.PHONY : src/Vec3.cpp.i

src/Vec3.s: src/Vec3.cpp.s

.PHONY : src/Vec3.s

# target to generate assembly for a file
src/Vec3.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/Vec3.cpp.s
.PHONY : src/Vec3.cpp.s

src/env.o: src/env.cpp.o

.PHONY : src/env.o

# target to build an object file
src/env.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/env.cpp.o
.PHONY : src/env.cpp.o

src/env.i: src/env.cpp.i

.PHONY : src/env.i

# target to preprocess a source file
src/env.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/env.cpp.i
.PHONY : src/env.cpp.i

src/env.s: src/env.cpp.s

.PHONY : src/env.s

# target to generate assembly for a file
src/env.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/env.cpp.s
.PHONY : src/env.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/shader.o: src/shader.cpp.o

.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i

.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s

.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

third-party/glad/glad.o: third-party/glad/glad.c.o

.PHONY : third-party/glad/glad.o

# target to build an object file
third-party/glad/glad.c.o:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/third-party/glad/glad.c.o
.PHONY : third-party/glad/glad.c.o

third-party/glad/glad.i: third-party/glad/glad.c.i

.PHONY : third-party/glad/glad.i

# target to preprocess a source file
third-party/glad/glad.c.i:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/third-party/glad/glad.c.i
.PHONY : third-party/glad/glad.c.i

third-party/glad/glad.s: third-party/glad/glad.c.s

.PHONY : third-party/glad/glad.s

# target to generate assembly for a file
third-party/glad/glad.c.s:
	$(MAKE) -f CMakeFiles/HumanGl.dir/build.make CMakeFiles/HumanGl.dir/third-party/glad/glad.c.s
.PHONY : third-party/glad/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... HumanGl"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... src/Bone.o"
	@echo "... src/Bone.i"
	@echo "... src/Bone.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Charactere.o"
	@echo "... src/Charactere.i"
	@echo "... src/Charactere.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Vec3.o"
	@echo "... src/Vec3.i"
	@echo "... src/Vec3.s"
	@echo "... src/env.o"
	@echo "... src/env.i"
	@echo "... src/env.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... third-party/glad/glad.o"
	@echo "... third-party/glad/glad.i"
	@echo "... third-party/glad/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

